### ISSUE TITLE
About #if WITH_EDITOR. 

### ISSUE THREAD

**Issue by unsanedingding** [AndreaCatania/RuntimeSkeletalMeshGenerator#26]
Can it work when the game is packaged and run?

**Comment by AndreaCatania** [comment]
I don't know if this works with UE5.4. Last time I used it with UE4.25 and it worked in packaged builds.

**Comment by unsanedingding** [comment]
Thank you.
There is only one way to verify the above problem, that is to package and run it, right?

**Comment by AndreaCatania** [comment]
Yes, correct
