### ISSUE TITLE
[bug] Model randomly is rendered wrong.

### ISSUE THREAD

**Issue by Fransferdy** [AndreaCatania/RuntimeSkeletalMeshGenerator#8]
Reopening here since I realized I wrote the issue in the wrong place.

Hello, thanks for providing this plugin. After testing for a while, I think the issue is with the plugin, but if it is not I would be glad to know how this is being used elsewhere.
So I started to use this plugin 4 days ago, I have been working to make a model procedurally. 
At the end of generation the function save the Model as a test.off file, call the plugin GenerateSkeletalMesh and return the result, which is then loaded in an Actor via blueprints. The blueprint run at Event Begin Play.
The output  teste.off file is always correct, you can load it in any tool to check that it is the same everytime, but the output from GenerateSkeletalMesh randomly changes. The function calculates the normals, tangents, uvs, set colors to (0,0,0) and flipnormals to false, set every vertex to the 0 bone.
My function outputs a cylinder/capsule model.
Sometimes the model is rendered correctly, but many times it is rendered in very weird patterns. On my side the result output is always the same, but in the engine the end result changes from play to play in bizarre ways.
You can see the code and the teste.off file here:
I also ported the plugin to UE5 (but the same issues happens in Ue4.27)
Can visualize the teste.off file here:https://3dviewer.net/
https://github.com/Fransferdy/creaturecreator

![Screenshot (11)](https://user-images.githubusercontent.com/6730735/157775729-cd3fc86d-1064-4629-a402-02706a5ca7a2.png)
![Screenshot (12)](https://user-images.githubusercontent.com/6730735/157775864-3e50193d-6dbd-4a20-aa4a-31158af5f4b9.png)
![Screenshot (13)](https://user-images.githubusercontent.com/6730735/157775867-0efe9db7-12e4-48ce-b2ba-7ff5c9b3148f.png)
![Screenshot (14)](https://user-images.githubusercontent.com/6730735/157775873-b1bdd7c2-aa2f-4886-8b5a-3ba35d6606a7.png)
![Screenshot (15)](https://user-images.githubusercontent.com/6730735/157775874-d56694d7-caf1-42ac-8fe0-cf30ecdd53e5.png)
![Screenshot (16)](https://user-images.githubusercontent.com/6730735/157775878-429dfe9b-9ccf-4343-9afd-44fb5fee7881.png)

**Comment by Fransferdy** [comment]
New Info, this only happens in the editor, in a packaged game it does not happen.

**Comment by AndreaCatania** [comment]
Hmm this is really interesting. So the same input renders a different output each time.

Can you please test this using UE4.27? This is an useful information to have. If it's confirmed an only UE5 issue then we should check how the data is layed out in UE5 or if we need to populate also another buffer.

**Comment by Fransferdy** [comment]
Yes, it is happening in Ue 4.27 as well:
I recorded a video to show the issue:
https://youtu.be/jchqYdma8I8
These are the blueprints:
(Every once second call GenerateBlob)
![ue4 blueprints](https://user-images.githubusercontent.com/6730735/158363143-ede38ff9-c35b-4b70-8e7e-a34f75e6fd7b.png)

Also, this is the code that loads the skeletal mesh:
meshSurfaces is a class member.
(here GenerateMyBlob(); creates the surface and adds it to the class instance member meshSurfaces, it only happens once, every subsequent call just uses the already created meshSurface)
```
USkeletalMesh* USkeletalMeshLoader::GenerateBlob(USkeleton* BaseSkeleton, TArray<UMaterialInterface*> mats) {

	UE_LOG(LogTemp, Warning, TEXT("Meshes: %d"), meshSurfaces.Num());
	if (meshSurfaces.Num() == 0)
	{
		GenerateMyBlob();
	}
	USkeletalMesh* skeletalMesh = NewObject<USkeletalMesh>();
	USkeleton* skeleton = NewObject<USkeleton>();
	buildSkeleton((FReferenceSkeleton&)skeleton->GetReferenceSkeleton(), skeleton);

	skeletalMesh->SetRefSkeleton(skeleton->GetReferenceSkeleton());
	skeletalMesh->SetSkeleton(skeleton);

	FRuntimeSkeletalMeshGenerator::GenerateSkeletalMesh(
		skeletalMesh,
		meshSurfaces,
		mats
	);

	return skeletalMesh;
}
```

**Comment by Fransferdy** [comment]
Not sure if it could have to do with hardware, but my machine is running Windows 10, with an i9 10900F, GTX 1060 6GB and 32 GB ram.

**Comment by Fransferdy** [comment]
Since this issue only happens inside the editor, I tried taking a look in the "WITHEDITOR" sections of the plugin, to see if I could pinpoint where the issue happens, but I didn't understand clearly all these parts, would you care to explain a  bit what it is that we have to do differently when inside the editor, versus the packaged game ? I also tried commenting out all those blocks, but that just crashes UE4/5 haha

**Comment by AndreaCatania** [comment]
Essentially the `WITH_EDITOR` is needed because those functions are not available in production, so it's necessary to not fill those items. If you can give me a sample project, so I can test it locally, I think I can give it a check and try to debug the issue. Otherwise it's a bit difficult to help you.

**Comment by Fransferdy** [comment]
There you go:
[SkeletalTest.zip](https://github.com/AndreaCatania/RuntimeSkeletalMeshGenerator/files/8261309/SkeletalTest.zip)

**Comment by LawlerZhang** [comment]
Hi, have you solved this issue? I found that the bug is caused by not initializing local variable ‘Weights’ defined in Line 429 in RuntimeSkeletalMeshGenerator.cpp

**Comment by Fransferdy** [comment]
No, I haven't, did you solve it ? After reading your comment I tried to call Weights.Empy() on line 430, but that didn't fix it.

**Comment by AndreaCatania** [comment]
Oh I see, so if a vertex doesn't not have any bind information it fails.
@Fransferdy Can you please try to loop the weights here https://github.com/AndreaCatania/RuntimeSkeletalMeshGenerator/blob/main/Source/RuntimeSkeletalMeshGenerator/RuntimeSkeletalMeshGenerator.cpp#L431

and reset all the influences for each weight using this:

````
					Weight.InfluenceWeights[InfluenceIndex] = 0;
					Weight.InfluenceBones[InfluenceIndex] = INDEX_NONE;
```

**Comment by Fransferdy** [comment]
I tried that this morning, but it did not solve the issue;

```
TArray<FSkinWeightInfo> Weights;
	Weights.Empty();
	Weights.SetNum(Vertices.Num());

	for (int32 weightIndex = 0; weightIndex < Weights.Num(); weightIndex++)
	{
		FSkinWeightInfo& Weight = Weights[weightIndex];
		for (int InfluenceIndex = 0; InfluenceIndex < MaxBoneInfluences; InfluenceIndex++)
		{
			Weight.InfluenceWeights[InfluenceIndex] = 0;
			Weight.InfluenceBones[InfluenceIndex] = INDEX_NONE;
		}
	}
```

**Comment by LawlerZhang** [comment]
@Fransferdy  I think maybe it should be written like this:
`for (int WeightIdx = 0; WeightIdx < Weights.Num(); WeightIdx++)
	{
		for (int InfluenceIdx= 0; InfluenceIndex< MAX_TOTAL_INFLUENCES; ++InfluenceIdx)
		{
			Weights[WeightIdx].InfluenceBones[InfluenceIdx] = INDEX_NONE;
			Weights[WeightIdx].InfluenceWeights[InfluenceIdx] = 0;
		}
	}`

**Comment by Fransferdy** [comment]
I can't see what exactly is the difference between the code @LawlerZhang posted, and the one I posted (except for this variable: MaxBoneInfluences, so I think this constant is the game changer MAX_TOTAL_INFLUENCES)
**Replacing my loop with his fixed the issue !** 
Thanks for the solution @LawlerZhang !!
I think the source code should be updated with his fix above @AndreaCatania .
